;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


gamewon_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; New song

@instruments:
	.word @env1,@env2,@env0,@env0
	.word @env1,@env2,@env0,@env0
	.word @env1,@env2,@env0,@env0

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$06
@env2:
	.byte $c0,$c2,$c4,$00,$02


; New song
@song0ch0:
	.byte $fb,$05
@song0ch0loop:
@ref0:
	.byte $84,$28,$81,$20,$81,$28,$81,$20,$81,$63,$28,$89,$60,$28,$81
@ref1:
	.byte $83,$20,$81,$28,$81,$20,$81,$28,$81,$28,$81,$19,$81,$19,$81
@ref2:
	.byte $00,$81,$1e,$81,$26,$81,$1e,$81,$63,$26,$89,$60,$26,$81
@ref3:
	.byte $83,$1e,$81,$26,$81,$21,$81,$26,$81,$1e,$21,$26,$2a,$2d,$32
@ref4:
	.byte $28,$81,$20,$81,$28,$81,$20,$81,$63,$28,$89,$60,$28,$81
	.byte $ff,$0f
	.word @ref1
@ref6:
	.byte $00,$81,$1f,$81,$23,$81,$26,$81,$2b,$81,$2f,$85,$2d,$81
@ref7:
	.byte $83,$21,$81,$28,$81,$21,$81,$2d,$81,$31,$81,$2d,$28,$25,$21
@ref8:
	.byte $70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81
	.byte $70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81
	.byte $ff,$10
	.word @ref8
	.byte $ff,$10
	.word @ref8
	.byte $ff,$10
	.word @ref8
	.byte $fd
	.word @song0ch0loop

; New song
@song0ch1:
@song0ch1loop:
@ref12:
	.byte $84,$2c,$81,$23,$81,$2d,$81,$23,$81,$63,$2c,$89,$60,$2c,$81
@ref13:
	.byte $83,$23,$81,$2d,$81,$23,$81,$2d,$81,$63,$2c,$89
@ref14:
	.byte $60,$2a,$81,$21,$81,$2c,$81,$21,$81,$63,$2a,$89,$60,$2a,$81
@ref15:
	.byte $83,$21,$81,$2c,$81,$25,$81,$2a,$81,$25,$26,$2a,$2d,$32,$2a
@ref16:
	.byte $2c,$81,$23,$81,$2d,$81,$23,$81,$63,$2c,$89,$60,$2c,$81
	.byte $ff,$0b
	.word @ref13
@ref18:
	.byte $60,$2b,$81,$23,$81,$26,$81,$2b,$81,$2f,$81,$32,$85,$31,$81
@ref19:
	.byte $83,$28,$81,$2d,$81,$28,$81,$31,$81,$34,$81,$31,$2d,$28,$25
	.byte $ff,$10
	.word @ref8
	.byte $ff,$10
	.word @ref8
	.byte $ff,$10
	.word @ref8
	.byte $ff,$10
	.word @ref8
	.byte $fd
	.word @song0ch1loop

; New song
@song0ch2:
@song0ch2loop:
@ref24:
	.byte $9f
@ref25:
	.byte $9f
@ref26:
	.byte $9f
@ref27:
	.byte $9f
@ref28:
	.byte $9f
@ref29:
	.byte $9f
@ref30:
	.byte $9f
@ref31:
	.byte $9f
@ref32:
	.byte $9f
@ref33:
	.byte $9f
@ref34:
	.byte $9f
@ref35:
	.byte $9f
	.byte $fd
	.word @song0ch2loop

; New song
@song0ch3:
@song0ch3loop:
@ref36:
	.byte $80,$0a,$81,$0c,$81,$82,$05,$81,$80,$0c,$81,$0a,$81,$0c,$81,$82
	.byte $05,$81,$80,$0c,$81
@ref37:
	.byte $0a,$81,$0c,$81,$82,$05,$81,$80,$0c,$81,$82,$05,$81,$05,$81,$05
	.byte $81,$05,$81
	.byte $ff,$10
	.word @ref36
@ref39:
	.byte $0a,$81,$0c,$81,$82,$05,$81,$80,$0c,$81,$0c,$81,$0a,$81,$82,$05
	.byte $81,$05,$81
	.byte $ff,$10
	.word @ref36
	.byte $ff,$10
	.word @ref37
	.byte $ff,$10
	.word @ref36
	.byte $ff,$10
	.word @ref39
@ref44:
	.byte $9f
@ref45:
	.byte $9f
@ref46:
	.byte $9f
@ref47:
	.byte $9f
	.byte $fd
	.word @song0ch3loop

; New song
@song0ch4:
@song0ch4loop:
@ref48:
	.byte $9f
@ref49:
	.byte $9f
@ref50:
	.byte $9f
@ref51:
	.byte $9f
@ref52:
	.byte $9f
@ref53:
	.byte $9f
@ref54:
	.byte $9f
@ref55:
	.byte $9f
@ref56:
	.byte $9f
@ref57:
	.byte $9f
@ref58:
	.byte $9f
@ref59:
	.byte $9f
	.byte $fd
	.word @song0ch4loop
