;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


gameover_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; New song

@instruments:
	.word @env1,@env0,@env6,@env0
	.word @env1,@env0,@env0,@env0
	.word @env2,@env0,@env0,@env0
	.word @env3,@env5,@env0,@env0
	.word @env4,@env0,@env0,@env0

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c0,$ca,$c9,$c8,$c9,$ca,$c9,$c8,$c7,$c6,$00,$09
@env2:
	.byte $c4,$c3,$c2,$c1,$c0,$00,$04
@env3:
	.byte $c8,$c7,$c6,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$0b
@env4:
	.byte $ca,$c8,$c6,$c4,$c2,$c0,$00,$05
@env5:
	.byte $c0,$c1,$c2,$c3,$00,$03
@env6:
	.byte $bf,$be,$bd,$03,$be,$bf,$c0,$02,$c0,$00,$00


; New song
@song0ch0:
	.byte $fb,$08
@song0ch0loop:
@ref0:
	.byte $80,$1a,$85,$19,$85,$1d,$85,$75,$19,$81,$7f,$1d,$81,$75,$1d,$81
	.byte $7f,$1c,$81,$75,$1d,$81,$7f,$1c,$81,$75,$1c,$81,$7f,$1a,$81,$19
	.byte $85
@ref1:
	.byte $1a,$85,$19,$85,$1d,$85,$75,$19,$81,$7f,$1d,$81,$75,$1d,$81,$7f
	.byte $1c,$81,$75,$1d,$81,$7f,$1c,$81,$75,$1c,$81,$7f,$1a,$81,$19,$85
	.byte $ff,$18
	.word @ref1
	.byte $ff,$18
	.word @ref1
@ref4:
	.byte $23,$85,$21,$85,$1f,$85,$25,$81,$25,$81,$75,$25,$81,$7f,$25,$81
	.byte $75,$25,$81,$7f,$23,$81,$75,$25,$81,$7f,$23,$81,$21,$85
	.byte $ff,$18
	.word @ref4
@ref6:
	.byte $26,$81,$25,$81,$75,$26,$81,$7f,$1f,$81,$75,$25,$81,$7f,$26,$81
	.byte $25,$81,$75,$26,$81,$7f,$1f,$85,$26,$81,$25,$81,$75,$26,$81,$7f
	.byte $1f,$81,$75,$25,$81,$1f,$81
@ref7:
	.byte $7f,$26,$81,$25,$81,$75,$26,$81,$7f,$1f,$81,$75,$25,$81,$7f,$26
	.byte $81,$25,$81,$75,$26,$81,$7f,$1f,$85,$26,$81,$25,$81,$75,$26,$81
	.byte $7f,$1f,$81,$75,$25,$81,$1f,$81
@ref8:
	.byte $75,$07,$81,$08,$81,$09,$81,$0a,$81,$7f,$09,$81,$0a,$81,$0b,$81
	.byte $0c,$81
@ref9:
	.byte $0b,$81,$0c,$81,$0d,$81,$0e,$81,$0d,$81,$0e,$81,$0f,$81,$10,$81
	.byte $ff,$18
	.word @ref1
	.byte $ff,$18
	.word @ref1
	.byte $fd
	.word @song0ch0loop

; New song
@song0ch1:
@song0ch1loop:
@ref12:
	.byte $80,$26,$85,$25,$85,$29,$85,$75,$25,$81,$7f,$29,$81,$75,$29,$81
	.byte $7f,$28,$81,$75,$29,$81,$7f,$28,$81,$75,$28,$81,$7f,$26,$81,$25
	.byte $85
@ref13:
	.byte $26,$85,$25,$85,$29,$85,$75,$25,$81,$7f,$29,$81,$75,$29,$81,$7f
	.byte $28,$81,$75,$29,$81,$7f,$28,$81,$75,$28,$81,$7f,$26,$81,$25,$85
	.byte $ff,$18
	.word @ref13
	.byte $ff,$18
	.word @ref13
@ref16:
	.byte $26,$85,$25,$85,$23,$85,$28,$81,$28,$81,$00,$81,$7f,$28,$81,$75
	.byte $28,$81,$7f,$26,$81,$00,$81,$7f,$26,$81,$25,$85
	.byte $ff,$18
	.word @ref16
@ref18:
	.byte $29,$81,$28,$81,$75,$29,$81,$7f,$25,$81,$00,$81,$29,$81,$28,$81
	.byte $00,$81,$25,$85,$29,$81,$28,$81,$00,$81,$7f,$25,$81,$75,$28,$81
	.byte $00,$81
@ref19:
	.byte $7f,$29,$81,$28,$81,$75,$29,$81,$7f,$25,$81,$00,$81,$29,$81,$28
	.byte $81,$00,$81,$25,$85,$29,$81,$28,$81,$00,$81,$7f,$25,$81,$75,$28
	.byte $81,$00,$81
@ref20:
	.byte $7f,$1f,$81,$20,$81,$21,$81,$22,$81,$21,$81,$22,$81,$23,$81,$24
	.byte $81
@ref21:
	.byte $23,$81,$24,$81,$25,$81,$26,$81,$25,$81,$26,$81,$27,$81,$28,$81
	.byte $ff,$18
	.word @ref13
	.byte $ff,$18
	.word @ref13
	.byte $fd
	.word @song0ch1loop

; New song
@song0ch2:
@song0ch2loop:
@ref24:
	.byte $82,$1a,$89,$1a,$81,$1a,$81,$1a,$85,$1a,$81,$1a,$81,$1a,$85,$1a
	.byte $81,$1a,$81,$1a,$85,$1a,$81
@ref25:
	.byte $1a,$81,$1a,$85,$1a,$81,$1a,$81,$1a,$85,$1a,$81,$1a,$81,$1a,$85
	.byte $1a,$81,$1a,$81,$1a,$85,$1a,$81
	.byte $ff,$18
	.word @ref25
	.byte $ff,$18
	.word @ref25
@ref28:
	.byte $1f,$81,$1f,$85,$1f,$81,$1f,$81,$1f,$85,$1f,$81,$1f,$81,$1f,$85
	.byte $1f,$81,$1f,$81,$1f,$85,$1f,$81
	.byte $ff,$18
	.word @ref28
	.byte $ff,$18
	.word @ref25
	.byte $ff,$18
	.word @ref25
@ref32:
	.byte $1f,$81,$20,$81,$21,$81,$22,$81,$21,$81,$22,$81,$23,$81,$24,$81
@ref33:
	.byte $17,$81,$18,$81,$19,$81,$1a,$81,$19,$81,$1a,$81,$1b,$81,$1c,$81
	.byte $ff,$18
	.word @ref25
	.byte $ff,$18
	.word @ref25
	.byte $fd
	.word @song0ch2loop

; New song
@song0ch3:
@song0ch3loop:
@ref36:
	.byte $83,$84,$0a,$0a,$86,$07,$07,$8b,$07,$85,$88,$10,$85,$86,$07,$85
	.byte $88,$10,$85,$86,$07,$85
@ref37:
	.byte $87,$07,$8d,$07,$85,$88,$10,$85,$86,$07,$85,$88,$10,$85,$86,$07
	.byte $85
	.byte $ff,$0d
	.word @ref37
	.byte $ff,$0d
	.word @ref37
	.byte $ff,$0d
	.word @ref37
	.byte $ff,$0d
	.word @ref37
@ref42:
	.byte $87,$07,$8d,$07,$8d,$07,$8d,$07,$81,$74,$82,$0a,$7f,$86,$07
	.byte $ff,$0b
	.word @ref42
@ref44:
	.byte $9f
@ref45:
	.byte $9f
	.byte $ff,$0d
	.word @ref37
	.byte $ff,$0d
	.word @ref37
	.byte $fd
	.word @song0ch3loop

; New song
@song0ch4:
@song0ch4loop:
@ref48:
	.byte $bf
@ref49:
	.byte $bf
@ref50:
	.byte $bf
@ref51:
	.byte $bf
@ref52:
	.byte $bf
@ref53:
	.byte $bf
@ref54:
	.byte $bf
@ref55:
	.byte $bf
@ref56:
	.byte $9f
@ref57:
	.byte $9f
@ref58:
	.byte $bf
@ref59:
	.byte $bf
	.byte $fd
	.word @song0ch4loop
